# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2023.11.17
_src_path: gh:scientific-python/cookie
backend: hatch
email: nstarman@users.noreply.github.com
full_name: Nathaniel Starkman
license: BSD
org: nstarman
project_name: analytic_mass_function
project_short_description: Sample from analytic mass functions
url: https://github.com/nstarman/analytic_mass_function
vcs: true
